### ISSUE TITLE
npm install errors

### ISSUE THREAD

**Issue by dotares** [OliverKovacs/wslrpc#1]
on `npm i`: 

```
npm ERR! code 1
npm ERR! git dep preparation failed
npm ERR! command /home/fibz/.nvm/versions/node/v20.4.0/bin/node /home/fibz/.nvm/versions/node/v20.4.0/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/home/fibz/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm ERR! > register-scheme@0.0.2 install
npm ERR! > node-gyp rebuild
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.4.0
npm ERR! gyp info using node@20.4.0 | linux | x64
npm ERR! gyp info find Python using Python version 3.10.6 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/home/fibz/.nvm/versions/node/v20.4.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/fibz/.npm/_cacache/tmp/git-cloneTKqV4i/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/fibz/.nvm/versions/node/v20.4.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/fibz/.cache/node-gyp/20.4.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/fibz/.cache/node-gyp/20.4.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/home/fibz/.nvm/versions/node/v20.4.0/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/fibz/.cache/node-gyp/20.4.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/fibz/.npm/_cacache/tmp/git-cloneTKqV4i',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: not found: make
npm ERR! gyp ERR! stack     at getNotFoundError (/home/fibz/.nvm/versions/node/v20.4.0/lib/node_modules/npm/node_modules/node-gyp/node_modules/which/which.js:10:17)
npm ERR! gyp ERR! stack     at /home/fibz/.nvm/versions/node/v20.4.0/lib/node_modules/npm/node_modules/node-gyp/node_modules/which/which.js:57:18
npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
npm ERR! gyp ERR! stack     at step (/home/fibz/.nvm/versions/node/v20.4.0/lib/node_modules/npm/node_modules/node-gyp/node_modules/which/which.js:54:21)
npm ERR! gyp ERR! stack     at /home/fibz/.nvm/versions/node/v20.4.0/lib/node_modules/npm/node_modules/node-gyp/node_modules/which/which.js:71:22
npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
npm ERR! gyp ERR! stack     at subStep (/home/fibz/.nvm/versions/node/v20.4.0/lib/node_modules/npm/node_modules/node-gyp/node_modules/which/which.js:69:33)
npm ERR! gyp ERR! stack     at /home/fibz/.nvm/versions/node/v20.4.0/lib/node_modules/npm/node_modules/node-gyp/node_modules/which/which.js:80:22
npm ERR! gyp ERR! stack     at /home/fibz/.nvm/versions/node/v20.4.0/lib/node_modules/npm/node_modules/isexe/index.js:42:5
npm ERR! gyp ERR! stack     at /home/fibz/.nvm/versions/node/v20.4.0/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
npm ERR! gyp ERR! System Linux 5.15.90.1-microsoft-standard-WSL2
npm ERR! gyp ERR! command "/home/fibz/.nvm/versions/node/v20.4.0/bin/node" "/home/fibz/.nvm/versions/node/v20.4.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /home/fibz/.npm/_cacache/tmp/git-cloneTKqV4i
npm ERR! gyp ERR! node -v v20.4.0
npm ERR! gyp ERR! node-gyp -v v9.4.0
npm ERR! gyp ERR! not ok
npm ERR! npm ERR! code 1
npm ERR! npm ERR! path /home/fibz/.npm/_cacache/tmp/git-cloneTKqV4i
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command sh -c node-gyp rebuild
npm ERR!
npm ERR! npm ERR! A complete log of this run can be found in: /home/fibz/.npm/_logs/2023-07-23T06_37_48_376Z-debug-0.log

npm ERR! A complete log of this run can be found in: /home/fibz/.npm/_logs/2023-07-23T06_37_45_027Z-debug-0.log
```

debug log: 

```0 verbose cli /home/fibz/.nvm/versions/node/v20.4.0/bin/node /home/fibz/.nvm/versions/node/v20.4.0/lib/node_modules/npm/bin/npm-cli.js
1 info using npm@9.8.0
2 info using node@v20.4.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/home/fibz/.nvm/versions/node/v20.4.0/lib/node_modules/npm/npmrc Completed in 0ms
6 timing config:load:builtin Completed in 0ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/home/fibz/.npm/_cacache/tmp/git-cloneTKqV4i/.npmrc Completed in 1ms
10 timing config:load:project Completed in 6ms
11 timing config:load:file:/home/fibz/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/home/fibz/.nvm/versions/node/v20.4.0/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 1ms
16 timing config:load Completed in 12ms
17 timing npm:load:configload Completed in 12ms
18 timing config:load:flatten Completed in 1ms
19 timing npm:load:mkdirpcache Completed in 0ms
20 timing npm:load:mkdirplogs Completed in 1ms
21 verbose title npm install
22 verbose argv "install" "--force" "--cache" "/home/fibz/.npm" "--prefer-offline" "false" "--prefer-online" "false" "--offline" "false" "--no-progress" "--no-save" "--no-audit" "--include" "dev" "--include" "peer" "--include" "optional" "--no-package-lock-only" "--no-dry-run"
23 timing npm:load:setTitle Completed in 1ms
24 timing npm:load:display Completed in 0ms
25 verbose logfile logs-max:10 dir:/home/fibz/.npm/_logs/2023-07-23T06_37_48_376Z-```

**Comment by OliverKovacs** [comment]
hey, could you please try running `sudo apt-get install build-essential` and then `npm i`?

**Comment by dotares** [comment]
@OliverKovacs That worked but Rich Presence still doesn't work.
